input {
  http {
    host => "0.0.0.0"
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "sentinel-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
